function upVideos(){
    var mainContent = document.getElementById("mainContentDash");
    html =  "<div class='block-header'>";
    html +=     "<h2>ANIE DASH</h2>";
    html += "</div>";
    html += "<div class='row clearfix'>";
    html +=     "<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>";
    html +=         "<div class='card'>";
    html +=         "<div class='header'>";
    html +=             "<h2>Upload de Episódios</h2>";
    html +=         "</div>";
    html +=         "<div class='body'>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-7'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<select class='form-control'>";
    html +=                                 "<option val='id'>Nome do Anime</option>";
    html +=                             "</select>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-6'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' class='form-control' placeholder='Nome do Episódio'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-6'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='number' class='form-control' placeholder='Número do Episódio'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=         "</div>";
    html +=     "</div>";
    html += "</div>"
    
    mainContent.innerHTML = html;
}

function novoAnime(idUser){
    var mainContent = document.getElementById("mainContentDash");
    html =  "<div class='block-header'>";
    html +=     "<h2>ANIE DASH</h2>";
    html += "</div>";
    html += "<div class='row clearfix'>";
    html +=     "<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>";
    html +=         "<div class='card'>";
    html +=         "<div class='header'>";
    html +=             "<h2>Novo Anime</h2>";
    html +=         "</div>";
    html +=         "<div class='body'>";
    html +=         "<form method='post' action='controllers/animes.php?novoAnime' enctype='multipart/form-data'>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' name='nomeAnime' class='form-control' placeholder='Nome do Anime'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' name='nomeAlternativo' class='form-control' placeholder='Nome alternativo'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='number' name='faixaEtaria' class='form-control' placeholder='Faixa etária'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='number' name='temporadaAtual' class='form-control' placeholder='Temporada Atual'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' name='nomeAlternativo' class='form-control' placeholder='Nome alternativo'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='number' name='faixaEtaria' class='form-control' placeholder='Faixa etária'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' name='nomePastaAnime' class='form-control' placeholder='Nome da pasta do Anime'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<input type='text' name='senha' class='form-control' placeholder='Sua senha'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=             "<div class='row clearfix'>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<label>Capa do Anime</label>";
    html +=                             "<input type='file' name='capaAnime' class='form-control'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<label>Background do Anime</label>";
    html +=                             "<input type='file' name='backAnime' class='form-control'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=                 "<div class='col-sm-4'>";
    html +=                     "<div class='form-group'>";
    html +=                         "<div class='form-line'>";
    html +=                             "<label>Logo do Anime</label>";
    html +=                             "<input type='file' name='logoAnime' class='form-control'>";
    html +=                         "</div>";
    html +=                     "</div>";
    html +=                 "</div>";
    html +=             "</div>";
    html +=         "<input type='hidden' name='id' value="+idUser+">";
    html +=         "</form>";
    html +=         "</div>";
    html +=     "</div>";
    html += "</div>"
    
    mainContent.innerHTML = html;
}